openapi: 3.0.1
info:
  title: RoomAlone
  description: A plugin that allows the user to play games of RoomAlone with ChatGPT. The game session is identified with a GUID, which is returned by the plugin when the game is started. The user can then use the GUID to continue the game later.
  version: 'v1'
servers:
  - url: http://localhost:8080
paths:
  /new_session:
    post:
      operationId: newSession
      summary: Start a new session.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/newSessionRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/newSessionResponse'

  /end_session/{session_guid}:
    get:
      operationId: endSession
      summary: Indicate that the player has won the game or otherwise wishes to terminate the session.
      parameters:
      - in: path
        name: session_guid
        schema:
          type: string
        required: true
        description: The GUID of the game session.
      responses:
        "200":
          description: OK

  /inventory/{session_guid}:
    get:
      operationId: getInventory
      summary: Get the current player inventory.
      parameters:
      - in: path
        name: session_guid
        schema:
          type: string
        required: true
        description: The GUID of the game session.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inventory'
    post:
      operationId: setInventory
      summary: Set the session inventory to keep track of items carried or worn.
      parameters:
      - in: path
        name: session_guid
        schema:
          type: string
        required: true
        description: The GUID of the game session.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/inventory'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inventory'

  /location/{session_guid}:
    get:
      operationId: getLocation
      summary: Get a description of the current location.
      parameters:
      - in: path
        name: session_guid
        schema:
          type: string
        required: true
        description: The GUID of the game session.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/location'
    put:
      operationId: setLocation
      summary: Create or update a full location description.
      parameters:
      - in: path
        name: session_guid
        schema:
          type: string
        required: true
        description: The GUID of the game session.
      requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/location'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/location'
    post:
      operationId: movePlayer
      summary: Move the player to a new location.
      parameters:
      - in: path
        name: session_guid
        schema:
          type: string
        required: true
        description: The GUID of the game session.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/moveRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/location'

components:
  schemas:
    newSessionRequest:
      type: object
      properties:
        adventure:
          type: string
          description: The name of the adventure to play. Options are charlie_noir and clever_engineer.
          required: true
    newSessionResponse:
      type: object
      properties:
        session_guid:
          type: string
          description: The GUID of the new session.
    inventory:
      type: array
      items:
        type: string
      description: The items in the player's inventory.
    location:
      type: object
      properties:
        name:
          type: string
          description: The name of the location
        connections:
          type: array
          items:
            type: string
          description: The names of the locations that can be reached from this location.
        description:
          type: string
          description: The description of the location.
        changes:
          type: array
          items:
            type: string
          description: The changes that the player has made to the location in this session.
        story:
          type: array
          items:
            type: string
          description: The story elements associated with the location. This may include plot points, items, and other elements.
    moveRequest:
      type: object
      required:
      - location
      properties:
        location:
          type: string
          description: The name of the new location.
          required: true